<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

/**
 * The ELD step's state on the onboarding request.
 *
 * `eld_skipped_at` is its own timestamp for the same reason the ID and bank
 * skips are: "declined to connect an ELD" and "has not reached that step" are
 * different facts, and a broker deciding whether to tender a load needs to tell
 * them apart.
 */
return new class extends Migration
{
    /**
     * Generated by Laravel from the table and column, so an earlier ELD
     * implementation on this table produced exactly the same name.
     */
    private const LEGACY_FOREIGN_KEY = 'carrier_connect_requests_eld_connection_id_foreign';

    public function up(): void
    {
        $this->clearLegacySchema();

        Schema::table('carrier_connect_requests', function (Blueprint $table) {
            $table->foreignId('eld_connection_id')
                ->nullable()
                ->after('bank_skipped_at')
                ->constrained('eld_connections')
                ->nullOnDelete();

            /*
            | The CSRF nonce handed to Terminal when the Link page is opened and
            | checked when the carrier comes back. Single use: cleared on the
            | exchange, so a replayed return URL finds nothing to match.
            */
            $table->string('eld_link_state', 64)->nullable()->after('eld_connection_id');
            $table->timestamp('eld_link_state_at')->nullable()->after('eld_link_state');

            $table->timestamp('eld_connected_at')->nullable()->after('eld_link_state_at');
            $table->timestamp('eld_skipped_at')->nullable()->after('eld_connected_at');
        });
    }

    /**
     * Make room on an environment that carried the previous ELD schema.
     *
     * Two things get in the way there. Renaming the old columns aside frees
     * their names but not the foreign key's — MySQL keeps a constraint name
     * through a column rename — so adding this one collides with a key that now
     * points at the parked column. And a run that failed on that collision has
     * already added `eld_connection_id`, which would then collide in its own
     * right on the retry.
     *
     * Both checks are no-ops on a fresh database, so this migration behaves
     * identically whether or not the old schema was ever there.
     */
    private function clearLegacySchema(): void
    {
        // information_schema is MySQL's; the test suite runs on sqlite, where
        // neither leftover can exist because nothing built the old schema.
        if (DB::getDriverName() === 'mysql') {
            $stale = DB::selectOne(
                'SELECT 1 AS found FROM information_schema.TABLE_CONSTRAINTS
                 WHERE CONSTRAINT_SCHEMA = DATABASE()
                   AND TABLE_NAME = ?
                   AND CONSTRAINT_NAME = ?',
                ['carrier_connect_requests', self::LEGACY_FOREIGN_KEY]
            );

            if ($stale) {
                DB::statement(
                    'ALTER TABLE `carrier_connect_requests` DROP FOREIGN KEY `'
                    .self::LEGACY_FOREIGN_KEY.'`'
                );
            }
        }

        if (Schema::hasColumn('carrier_connect_requests', 'eld_connection_id')) {
            Schema::table('carrier_connect_requests', function (Blueprint $table) {
                $table->dropColumn('eld_connection_id');
            });
        }
    }

    public function down(): void
    {
        Schema::table('carrier_connect_requests', function (Blueprint $table) {
            $table->dropForeign(['eld_connection_id']);
            $table->dropColumn([
                'eld_connection_id',
                'eld_link_state',
                'eld_link_state_at',
                'eld_connected_at',
                'eld_skipped_at',
            ]);
        });
    }
};
