<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Devices a carrier ticked "remember this device" on. While a row here is
     * live, that device skips the login OTP.
     */
    public function up(): void
    {
        Schema::create('carrier_trusted_devices', function (Blueprint $table) {

            $table->id();

            $table->foreignId('carrier_user_id')
                ->constrained('carrier_users')
                ->cascadeOnDelete();

            // Generated by the client. Unique per account, not globally: the
            // same shared machine can be trusted by two carriers.
            $table->string('device_uuid', 100);

            $table->string('device_name')->nullable();

            $table->string('browser')->nullable();

            $table->string('platform')->nullable();

            $table->ipAddress('ip_address')->nullable();

            $table->timestamp('last_used_at')->nullable();

            $table->timestamp('expires_at')->nullable();

            $table->timestamps();

            $table->unique(['carrier_user_id', 'device_uuid']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('carrier_trusted_devices');
    }
};
