<?php

namespace App\Models\Carriers;

use Illuminate\Database\Eloquent\Model;

class CarrierDetail extends Model
{
    /**
     * Lives in the carrier database on EC2, not the local database.
     */
    protected $connection = 'external_db';

    protected $table = 'carrier_details';

    protected $fillable = [
        'row_id',
        'dot_number',
        'status_code',
        'dun_bradstreet_no',
        'phy_omc_region',
        'safety_inv_terr',
        'business_org_id',
        'business_org_desc',
        'mcs150_update_code_id',
        'mcs151_mileage',
        'prior_revoke_flag',
        'prior_revoke_dot_number',
        'phone',
        'fax',
        'cell_phone',
        'company_officer_1',
        'company_officer_2',
        'total_cars',
        'truck_units',
        'power_units',
        'bus_units',
        'fleetsize',
        'review_id',
        'review_type',
        'review_date',
        'safety_rating',
        'safety_rating_date',
        'recordable_crash_rate',
        'mail_nationality_indicator',
        'phy_nationality_indicator',
        'phy_barrio',
        'mail_barrio',
        'carship',
        'docket1prefix',
        'docket1',
        'docket1_status_code',
        'docket2prefix',
        'docket2',
        'docket2_status_code',
        'docket3prefix',
        'docket3',
        'docket3_status_code',
        'pointnum',
        'mcsipstep',
        'mcsipdate',
        'total_intrastate_drivers',
        'total_cdl',
        'total_drivers',
        'avg_drivers_leased_per_month',
        'driver_inter_total',
        'hm_ind',
        'interstate_beyond_100_miles',
        'interstate_within_100_miles',
        'intrastate_beyond_100_miles',
        'intrastate_within_100_miles',
        'classdef',
        'carrier_mailing_street',
        'carrier_mailing_state',
        'carrier_mailing_city',
        'carrier_mailing_country',
        'carrier_mailing_zip',
        'carrier_mailing_cnty',
        'carrier_mailing_und_date',
        'phy_cnty',
        'undeliv_phy',
        'crgo_genfreight',
        'crgo_household',
        'crgo_metalsheet',
        'crgo_motoveh',
        'crgo_drivetow',
        'crgo_logpole',
        'crgo_bldgmat',
        'crgo_mobilehome',
        'crgo_machlrg',
        'crgo_produce',
        'crgo_liqgas',
        'crgo_intermodal',
        'crgo_passengers',
        'crgo_oilfield',
        'crgo_livestock',
        'crgo_grainfeed',
        'crgo_coalcoke',
        'crgo_meat',
        'crgo_garbage',
        'crgo_usmail',
        'crgo_chem',
        'crgo_drybulk',
        'crgo_coldfood',
        'crgo_beverages',
        'crgo_paperprod',
        'crgo_utility',
        'crgo_farmsupp',
        'crgo_construct',
        'crgo_waterwell',
        'crgo_cargoothr',
        'crgo_cargoothr_desc',
        'owntruck',
        'owntract',
        'owntrail',
        'owncoach',
        'ownschool_1_8',
        'ownschool_9_15',
        'ownschool_16',
        'ownbus_16',
        'ownvan_1_8',
        'ownvan_9_15',
        'ownlimo_1_8',
        'ownlimo_9_15',
        'ownlimo_16',
        'trmtruck',
        'trmtract',
        'trmtrail',
        'trmcoach',
        'trmschool_1_8',
        'trmschool_9_15',
        'trmschool_16',
        'trmbus_16',
        'trmvan_1_8',
        'trmvan_9_15',
        'trmlimo_1_8',
        'trmlimo_9_15',
        'trmlimo_16',
        'trptruck',
        'trptract',
        'trptrail',
        'trpcoach',
        'trpschool_1_8',
        'trpschool_9_15',
        'trpschool_16',
        'trpbus_16',
        'trpvan_1_8',
        'trpvan_9_15',
        'trplimo_1_8',
        'trplimo_9_15',
        'trplimo_16',
    ];

    public function carrier()
    {
        return $this->belongsTo(Carrier::class, 'dot_number', 'dot_number');
    }
}
