name: Deploy Laravel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: ${{ secrets.EC2_PORT }}

          script: |
            cd /var/www/dollartraqapi

            git fetch origin
            git reset --hard origin/main

            composer install --no-dev --prefer-dist --optimize-autoloader

            php artisan migrate

            php artisan config:cache
            php artisan route:cache
            php artisan view:cache

            php artisan optimize

            sudo systemctl reload apache2
